volumes:
  noisemodelling-db:
    driver: local

services:
    noisemodelling:
      image: ghcr.io/universite-gustave-eiffel/plamade:main
      restart: unless-stopped
      ports:
        - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/nmcovadis"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
      volumes:
        - noisemodelling-db:/srv/noisemodelling/workspace